name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
          components: rustfmt,clippy
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check linting
      run: cargo clippy --all-features -- -D warnings
    - name: Build
      run: cargo build --all-features
    - name: Run tests
      run: cargo test  --all-features
    - name: Docs
      run: cargo doc --all-features --document-private-items
